### ISSUE TITLE
TODO APP 요구사항 명세서 작성 - [03] 수정

### ISSUE THREAD

**Issue by yeri134** [yeri134/pretodoapp#3]
### 수정 기능

1. [ ] 리스트에서 수정 할 리스트 선택
2. [ ] 선택 후 정보 수정 기능
3. [ ] 수정 후 리스트에 변경 표시
