### ISSUE TITLE
TODO APP 요구사항 명세서 작성 - [04] 삭제

### ISSUE THREAD

**Issue by yeri134** [yeri134/pretodoapp#4]
### 삭제 기능

1. [ ] 리스트에서 삭제 할 일 선택
2. [ ] 선택 버튼 만들기
3. [ ] 선택 할 일 삭제 구현
4. [ ] 리스트에서 제거
